In [14]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pandas as pd
print(tf.__version__)

1.3.0


In [15]:
a = tf.constant(2)
b = tf.constant(3)

mat1 = tf.constant ([[1,3,2],
                    [1,0,0],
                    [1,2,2]])
mat2 = tf.constant ([[1,0,5],
                    [7,5,0],
                    [2,1,1]])

In [13]:
suma = tf.add(a,b)
mult = tf.multiply(a,b)
cubo = a ** 3
suma_mat = tf.add(mat1,mat2)
mult_mat = tf.matmul(mat1,mat2)


In [17]:
with tf.Session() as sess:
    print("Suma de constantes: {}".format(sess.run(suma)))
    print("Multiplicacion de constantes: {}".format(sess.run(mult)))
    print("Constante elevada al cubo: {}".format(sess.run(cubo)))
    print("Suma de matrices: \n{}".format(sess.run(suma_mat)))
    print("Producto de matrices:\n {}".format(sess.run(mult_mat)))

Suma de constantes: 5
Multiplicacion de constantes: 6
Constante elevada al cubo: 8
Suma de matrices: 
[[2 3 7]
 [8 5 0]
 [3 3 3]]
Producto de matrices:
 [[26 17  7]
 [ 1  0  5]
 [19 12  7]]


In [22]:
estado = tf.Variable(0,name = "contador")
uno = tf.constant(1)
nuevo_valor = tf.add(estado,uno)
actualizar = tf.assign(estado, nuevo_valor)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(estado))
    for _ in range(3):
        sess.run(actualizar)
        print(sess.run(estado))


0
1
2
3


In [23]:
x = tf.placeholder(tf.float32,shape = (4,4))
y = tf.matmul(x,x)
with tf.Session() as sess:
    rand_array = np.random.rand(4,4)
    print(sess.run(y,feed_dict = {x:rand_array}))
    

[[ 0.94252837  1.60007906  0.63597119  0.80755377]
 [ 0.55066651  1.12560809  0.30795226  0.59432375]
 [ 0.52021754  1.03809929  0.39479533  0.61338913]
 [ 0.44450384  0.87651139  0.39253822  0.64713699]]
